% INITSILOP Inicializa el sistema de procesamiento de las aplicaciones estandar de la toolbox
%
% INITSILOP Inicializa el sistema de procesamiento de las aplicaciones estandar de la toolbox. 
% Debe ser el primer comando usado en dichas aplicaciones.
% 
% Syntax: 
%   CONFIG=initsilop();
%
%   Parámetros de entrada: Ninguno
%   Parámetros de salida: 
%	CONFIG  Estructura de configuración de los sensores y algoritmos de la aplicación	
% 
% Examples: 
%   
%
% See also: 

% Author:   Antonio López
% History:  24.01.2008  creado
%           24.01.2008 Incorporado a la toolbox
%


function CONFIG = initsilop()

%Tamaño de la ventana de datos
CONFIG.GLOBAL.LONGITUDVENTANA = 1000;

%Números de serie de todos los posibles sensores que se pueden usar
CONFIG.SENHALES.COG.Serie = -1;
CONFIG.SENHALES.PIE_IZDO.Serie = -1;
CONFIG.SENHALES.PIE_DCHO.Serie = -1;
CONFIG.SENHALES.MUSLO_IZDO.Serie = -1;
CONFIG.SENHALES.MUSLO_DCHO.Serie = -1;
CONFIG.SENHALES.TIBIA_IZDA.Serie = -1;
CONFIG.SENHALES.TIBIA_DCHA.Serie = -1;


%Posición de cada señal en la matriz de datos

CONFIG.SENHALES.COG.Acc_Z = -1;
CONFIG.SENHALES.COG.Acc_Y = -1;
CONFIG.SENHALES.COG.Acc_X = -1;
CONFIG.SENHALES.COG.G_Z = -1;
CONFIG.SENHALES.COG.G_Y = -1;
CONFIG.SENHALES.COG.G_X = -1;
CONFIG.SENHALES.COG.MG_Z = -1;
CONFIG.SENHALES.COG.MG_Y = -1;
CONFIG.SENHALES.COG.MG_X = -1;

CONFIG.SENHALES.MUSLO_DCHO.Acc_Z = -1;
CONFIG.SENHALES.MUSLO_DCHO.Acc_Y = -1;
CONFIG.SENHALES.MUSLO_DCHO.Acc_X = -1;
CONFIG.SENHALES.MUSLO_DCHO.G_Z = -1;
CONFIG.SENHALES.MUSLO_DCHO.G_Y = -1;
CONFIG.SENHALES.MUSLO_DCHO.G_X = -1;
CONFIG.SENHALES.MUSLO_DCHO.MG_Z = -1;
CONFIG.SENHALES.MUSLO_DCHO.MG_Y = -1;
CONFIG.SENHALES.MUSLO_DCHO.MG_X = -1;

CONFIG.SENHALES.MUSLO_IZDO.Acc_Z = -1;
CONFIG.SENHALES.MUSLO_IZDO.Acc_Y = -1;
CONFIG.SENHALES.MUSLO_IZDO.Acc_X = -1;
CONFIG.SENHALES.MUSLO_IZDO.G_Z = -1;
CONFIG.SENHALES.MUSLO_IZDO.G_Y = -1;
CONFIG.SENHALES.MUSLO_IZDO.G_X = -1;
CONFIG.SENHALES.MUSLO_IZDO.MG_Z = -1;
CONFIG.SENHALES.MUSLO_IZDO.MG_Y = -1;
CONFIG.SENHALES.MUSLO_IZDO.MG_X = -1;

CONFIG.SENHALES.TIBIA_DCHA.Acc_Z = -1;
CONFIG.SENHALES.TIBIA_DCHA.Acc_Y = -1;
CONFIG.SENHALES.TIBIA_DCHA.Acc_X = -1;
CONFIG.SENHALES.TIBIA_DCHA.G_Z = -1;
CONFIG.SENHALES.TIBIA_DCHA.G_Y = -1;
CONFIG.SENHALES.TIBIA_DCHA.G_X = -1;
CONFIG.SENHALES.TIBIA_DCHA.MG_Z = -1;
CONFIG.SENHALES.TIBIA_DCHA.MG_Y = -1;
CONFIG.SENHALES.TIBIA_DCHA.MG_X = -1;

CONFIG.SENHALES.TIBIA_IZDA.Acc_Z = -1;
CONFIG.SENHALES.TIBIA_IZDA.Acc_Y = -1;
CONFIG.SENHALES.TIBIA_IZDA.Acc_X = -1;
CONFIG.SENHALES.TIBIA_IZDA.G_Z = -1;
CONFIG.SENHALES.TIBIA_IZDA.G_Y = -1;
CONFIG.SENHALES.TIBIA_IZDA.G_X = -1;
CONFIG.SENHALES.TIBIA_IZDA.MG_Z = -1;
CONFIG.SENHALES.TIBIA_IZDA.MG_Y = -1;
CONFIG.SENHALES.TIBIA_IZDA.MG_X = -1;

CONFIG.SENHALES.PIE_DCHO.Acc_Z = -1;
CONFIG.SENHALES.PIE_DCHO.Acc_Y = -1;
CONFIG.SENHALES.PIE_DCHO.Acc_X = -1;
CONFIG.SENHALES.PIE_DCHO.G_Z = -1;
CONFIG.SENHALES.PIE_DCHO.G_Y = -1;
CONFIG.SENHALES.PIE_DCHO.G_X = -1;
CONFIG.SENHALES.PIE_DCHO.MG_Z = -1;
CONFIG.SENHALES.PIE_DCHO.MG_Y = -1;
CONFIG.SENHALES.PIE_DCHO.MG_X = -1;

CONFIG.SENHALES.PIE_IZDO.Acc_Z = -1;
CONFIG.SENHALES.PIE_IZDO.Acc_Y = -1;
CONFIG.SENHALES.PIE_IZDO.Acc_X = -1;
CONFIG.SENHALES.PIE_IZDO.G_Z = -1;
CONFIG.SENHALES.PIE_IZDO.G_Y = -1;
CONFIG.SENHALES.PIE_IZDO.G_X = -1;
CONFIG.SENHALES.PIE_IZDO.MG_Z = -1;
CONFIG.SENHALES.PIE_IZDO.MG_Y = -1;
CONFIG.SENHALES.PIE_IZDO.MG_X = -1;

CONFIG.SENHALES.NUMEROSENHALES = 0;


%Datos generales del bus
CONFIG.BUS.Xbus = -1;
CONFIG.BUS.Temporizador = -1;
CONFIG.BUS.File = -1;

%Datos de los algoritmos usados
CONFIG.ALGORITMOS = [];
CONFIG.GLOBAL.COLUMNADISPONIBLE = -1;


